name: "CI"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  default:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: "Get pnpm store directory"
        id: "pnpm-cache"
        run: echo "::set-output name=pnpm_store_path::$(pnpm store path)"

      - name: Set "up pnpm cache"
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Lint Source
        run: pnpm exec biome ci
